### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by aryan2621** [imjohnzakkam/cc-analyzer#1]
1-> Can add the topicwise the question the user did like greedy,binary_search,dp and so on;
2-> numebrs of question done in each topic by user.

**Comment by imjohnzakkam** [comment]
I'm sorry replying to you after so long, it is very hard to get the topic wise questions solved by each user and the number of questions in the CodeChef API so we think it can't be done, but thanks for your idea! If you want you can fork and request a pull, would be glad ;)
