### ISSUE TITLE
everyday working map

### ISSUE THREAD

**Issue by anmolrajsoni15** [imjohnzakkam/cc-analyzer#2]
@imjohnzakkam,  This is the most important part which almost everyone wants i.e. heat map of numbers of question solved per day like present in Codeforces and Leetcode.

**Comment by imjohnzakkam** [comment]
I'm sorry replying to you after so long, it is very hard to get the problems solved by each user in the CodeChef API so we think it can't be done, but thanks for your idea! If you want you can fork and request a pull, would be glad ;)
